sudo: false
language: node_js
node_js:
  - "11.x"
  - "10.x"
  - "9.x"
  - "8.x"
  - "0.12"
  - "0.11"
  - "4.2"
  - "5.2"
  - "iojs"
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang  
